### ISSUE TITLE
Default Route (All-Traffic (0/0)) not propagating to respective attached subnet's route table 

### ISSUE THREAD

**Issue by mariomic-maker** [awslabs/serverless-transit-network-orchestrator#10] opened 2020-08-07 16:15 UTC
Hi,

I have setup the hub and spoke successfully.  However when attaching an existing subnet of an associated VPC to the transit gateway (using the Attach-to-tgw tag) , the route table of that subnet is not updated to point all traffic to the TGW (as set in the parameters on the hub stack creation i.e. All-traffic (0/0)

Am I missing something here? 

![image](https://user-images.githubusercontent.com/69359575/89665783-7de6c500-d8d9-11ea-848d-7c9fa4c0f8a7.png)

Would appreciate if something can assist with this please.

**Comment by groverlalit** [comment] 2020-08-11 20:23
@mariomic-maker Thanks for reaching out to us. Can you please confirm that the subnet you tagged didn't already have an existing default route in the the associated route table. By design, the solution does no overwrite existing default routes.

**Comment by maykays** [comment] 2020-09-21 18:29
Closing issue. Please confirm that the subnet you tagged didn't already have an existing default route in the the associated route table, and re-open if the issue persists.

**Closed by maykays** 2020-09-21 18:29 UTC
