### ISSUE TITLE
Provide SSO options for the portal instead of username/password

### ISSUE THREAD

**Issue by alFReD-NSH** [awslabs/serverless-transit-network-orchestrator#7] opened 2020-05-28 10:02 UTC
Having another password to share and rotate makes keeps me awake at nights. Ideally hub account administrators should be able to view the portal without any additional passwords or authentication via saml or other providers could be provided.
The fact that the portal is exposed to world via CloudFront, doesn't make things any easier.

**Comment by groverlalit** [comment] 2020-06-01 18:53
Thanks for request this feature. We have added this to our backlog.

**Comment by maykays** [comment] 2021-01-25 17:47
Duplicate of #27

**Closed by maykays** 2021-01-25 17:47 UTC
Labels: enhancement
